// Code generated by "cmd/builder"; DO NOT EDIT.

// Command querier is the generated OpenTelemetry Querier distribution
// entrypoint. It loads a runtime config, assembles the pipelines from the
// compiled-in factories (see components.go), and runs them.
package main

import (
	"context"
	"flag"
	"log"
	"os"
	"os/signal"
	"syscall"
	"time"

	"github.com/minuk-dev/opentelemetry-querier/component"
	"github.com/minuk-dev/opentelemetry-querier/querier"
)

var buildInfo = component.BuildInfo{Command: "querier", Version: "dev"}

func main() {
	configPath := flag.String("config", "config.yaml", "path to the runtime config file")
	flag.Parse()

	cfg, err := querier.LoadConfig(*configPath)
	if err != nil {
		log.Fatalf("querier: %v", err)
	}

	factories, err := components()
	if err != nil {
		log.Fatalf("querier: %v", err)
	}

	svc, err := querier.Build(factories, cfg, buildInfo)
	if err != nil {
		log.Fatalf("querier: %v", err)
	}

	ctx, stop := signal.NotifyContext(context.Background(), syscall.SIGINT, syscall.SIGTERM)
	defer stop()

	if err := svc.Start(ctx); err != nil {
		log.Fatalf("querier: %v", err)
	}
	log.Printf("querier: started with config %s", *configPath)

	<-ctx.Done()
	log.Printf("querier: shutting down")

	shutdownCtx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()
	if err := svc.Shutdown(shutdownCtx); err != nil {
		log.Printf("querier: shutdown error: %v", err)
		os.Exit(1)
	}
}
