// Command builder is a small analogue of the opentelemetry-collector-builder
// (ocb). It reads a builder.yaml manifest listing the acceptor / processor /
// dispatcher components to include, and generates the distribution's entrypoint
// (main.go) and factory registration (components.go) under dist.output_path.
//
// This realizes the two-layer model: builder.yaml selects components at build
// time; the generated distribution then reads a runtime config.yaml to
// instantiate and wire them into pipelines.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"log"
	"os"
	"path"
	"path/filepath"
	"strings"
	"text/template"

	"gopkg.in/yaml.v3"
)

// Manifest is the builder.yaml schema.
type Manifest struct {
	Dist struct {
		Name        string `yaml:"name"`
		Description string `yaml:"description"`
		Module      string `yaml:"module"`
		Version     string `yaml:"version"`
		OutputPath  string `yaml:"output_path"`
	} `yaml:"dist"`
	Acceptors   []Component `yaml:"acceptors"`
	Processors  []Component `yaml:"processors"`
	Dispatchers []Component `yaml:"dispatchers"`
}

// Component is one selected component, identified by its Go module/import path.
type Component struct {
	GoMod string `yaml:"gomod"`
}

// tmplComponent is the view passed to templates.
type tmplComponent struct {
	Alias  string // import alias, e.g. "otqp"
	Import string // import path (version stripped)
}

type tmplData struct {
	Module      string
	Version     string
	Command     string
	Acceptors   []tmplComponent
	Processors  []tmplComponent
	Dispatchers []tmplComponent
}

func main() {
	configPath := flag.String("config", "builder.yaml", "path to the builder manifest")
	flag.Parse()

	m, err := loadManifest(*configPath)
	if err != nil {
		log.Fatalf("builder: %v", err)
	}

	data := tmplData{
		Module:      m.Dist.Module,
		Version:     orDefault(m.Dist.Version, "dev"),
		Command:     orDefault(m.Dist.Name, "querier"),
		Acceptors:   toTmpl(m.Acceptors),
		Processors:  toTmpl(m.Processors),
		Dispatchers: toTmpl(m.Dispatchers),
	}

	outDir := m.Dist.OutputPath
	if outDir == "" {
		outDir = "./cmd/querier"
	}
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		log.Fatalf("builder: mkdir %s: %v", outDir, err)
	}

	for name, tmpl := range map[string]*template.Template{
		"components.go": componentsTmpl,
		"main.go":       mainTmpl,
	} {
		if err := render(filepath.Join(outDir, name), tmpl, data); err != nil {
			log.Fatalf("builder: generate %s: %v", name, err)
		}
	}
	log.Printf("builder: generated distribution %q in %s", data.Command, outDir)
}

func loadManifest(path string) (*Manifest, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("read manifest %s: %w", path, err)
	}
	var m Manifest
	dec := yaml.NewDecoder(bytes.NewReader(raw))
	dec.KnownFields(true)
	if err := dec.Decode(&m); err != nil {
		return nil, fmt.Errorf("parse manifest %s: %w", path, err)
	}
	if m.Dist.Module == "" {
		return nil, fmt.Errorf("manifest dist.module is required")
	}
	return &m, nil
}

// toTmpl derives an import alias (the last path element, sanitized) for each
// component, stripping any "@version" suffix from the gomod path.
func toTmpl(cs []Component) []tmplComponent {
	out := make([]tmplComponent, 0, len(cs))
	for _, c := range cs {
		imp := c.GoMod
		if at := strings.IndexByte(imp, '@'); at >= 0 {
			imp = imp[:at]
		}
		if sp := strings.IndexByte(imp, ' '); sp >= 0 {
			imp = imp[:sp]
		}
		alias := sanitizeAlias(path.Base(imp))
		out = append(out, tmplComponent{Alias: alias, Import: imp})
	}
	return out
}

func sanitizeAlias(s string) string {
	var b strings.Builder
	for _, r := range s {
		if r == '-' || r == '.' {
			continue
		}
		b.WriteRune(r)
	}
	return b.String()
}

func render(outPath string, tmpl *template.Template, data tmplData) error {
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return err
	}
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return fmt.Errorf("gofmt: %w\n%s", err, buf.String())
	}
	return os.WriteFile(outPath, formatted, 0o644)
}

func orDefault(v, def string) string {
	if v == "" {
		return def
	}
	return v
}

var componentsTmpl = template.Must(template.New("components").Parse(`// Code generated by "cmd/builder"; DO NOT EDIT.

package main

import (
	"{{ .Module }}/acceptor"
	"{{ .Module }}/dispatcher"
	"{{ .Module }}/processor"
	"{{ .Module }}/querier"
{{- range .Acceptors }}
	{{ .Alias }} "{{ .Import }}"
{{- end }}
{{- range .Processors }}
	{{ .Alias }} "{{ .Import }}"
{{- end }}
{{- range .Dispatchers }}
	{{ .Alias }} "{{ .Import }}"
{{- end }}
)

// components registers the factories selected in builder.yaml.
func components() (querier.Factories, error) {
	var factories querier.Factories
	var err error

	if factories.Acceptors, err = acceptor.MakeFactoryMap(
{{- range .Acceptors }}
		{{ .Alias }}.NewFactory(),
{{- end }}
	); err != nil {
		return factories, err
	}

	if factories.Processors, err = processor.MakeFactoryMap(
{{- range .Processors }}
		{{ .Alias }}.NewFactory(),
{{- end }}
	); err != nil {
		return factories, err
	}

	if factories.Dispatchers, err = dispatcher.MakeFactoryMap(
{{- range .Dispatchers }}
		{{ .Alias }}.NewFactory(),
{{- end }}
	); err != nil {
		return factories, err
	}

	return factories, nil
}
`))

var mainTmpl = template.Must(template.New("main").Parse(`// Code generated by "cmd/builder"; DO NOT EDIT.

// Command {{ .Command }} is the generated OpenTelemetry Querier distribution
// entrypoint. It loads a runtime config, assembles the pipelines from the
// compiled-in factories (see components.go), and runs them.
package main

import (
	"context"
	"flag"
	"log"
	"os"
	"os/signal"
	"syscall"
	"time"

	"{{ .Module }}/component"
	"{{ .Module }}/querier"
)

var buildInfo = component.BuildInfo{Command: "{{ .Command }}", Version: "{{ .Version }}"}

func main() {
	configPath := flag.String("config", "config.yaml", "path to the runtime config file")
	flag.Parse()

	cfg, err := querier.LoadConfig(*configPath)
	if err != nil {
		log.Fatalf("{{ .Command }}: %v", err)
	}

	factories, err := components()
	if err != nil {
		log.Fatalf("{{ .Command }}: %v", err)
	}

	svc, err := querier.Build(factories, cfg, buildInfo)
	if err != nil {
		log.Fatalf("{{ .Command }}: %v", err)
	}

	ctx, stop := signal.NotifyContext(context.Background(), syscall.SIGINT, syscall.SIGTERM)
	defer stop()

	if err := svc.Start(ctx); err != nil {
		log.Fatalf("{{ .Command }}: %v", err)
	}
	log.Printf("{{ .Command }}: started with config %s", *configPath)

	<-ctx.Done()
	log.Printf("{{ .Command }}: shutting down")

	shutdownCtx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()
	if err := svc.Shutdown(shutdownCtx); err != nil {
		log.Printf("{{ .Command }}: shutdown error: %v", err)
		os.Exit(1)
	}
}
`))
