// Code generated by "cmd/builder"; DO NOT EDIT.

package main

import (
	"github.com/minuk-dev/opentelemetry-querier/acceptor"
	otqp "github.com/minuk-dev/opentelemetry-querier/acceptor/otqp"
	prometheusacceptor "github.com/minuk-dev/opentelemetry-querier/acceptor/prometheusacceptor"
	"github.com/minuk-dev/opentelemetry-querier/dispatcher"
	promdispatcher "github.com/minuk-dev/opentelemetry-querier/dispatcher/promdispatcher"
	"github.com/minuk-dev/opentelemetry-querier/processor"
	authratelimit "github.com/minuk-dev/opentelemetry-querier/processor/authratelimit"
	queryrewrite "github.com/minuk-dev/opentelemetry-querier/processor/queryrewrite"
	responsefilter "github.com/minuk-dev/opentelemetry-querier/processor/responsefilter"
	simpleauthz "github.com/minuk-dev/opentelemetry-querier/processor/simpleauthz"
	tenant "github.com/minuk-dev/opentelemetry-querier/processor/tenant"
	"github.com/minuk-dev/opentelemetry-querier/querier"
)

// components registers the factories selected in builder.yaml.
func components() (querier.Factories, error) {
	var factories querier.Factories
	var err error

	if factories.Acceptors, err = acceptor.MakeFactoryMap(
		otqp.NewFactory(),
		prometheusacceptor.NewFactory(),
	); err != nil {
		return factories, err
	}

	if factories.Processors, err = processor.MakeFactoryMap(
		authratelimit.NewFactory(),
		tenant.NewFactory(),
		queryrewrite.NewFactory(),
		responsefilter.NewFactory(),
		simpleauthz.NewFactory(),
	); err != nil {
		return factories, err
	}

	if factories.Dispatchers, err = dispatcher.MakeFactoryMap(
		promdispatcher.NewFactory(),
	); err != nil {
		return factories, err
	}

	return factories, nil
}
