// Code generated by "cmd/builder"; DO NOT EDIT.

package main

import (
	"github.com/minuk-dev/opentelemetry-querier/acceptor"
	lokiacceptor "github.com/minuk-dev/opentelemetry-querier/acceptor/lokiacceptor"
	otqpacceptor "github.com/minuk-dev/opentelemetry-querier/acceptor/otqpacceptor"
	prometheusacceptor "github.com/minuk-dev/opentelemetry-querier/acceptor/prometheusacceptor"
	"github.com/minuk-dev/opentelemetry-querier/dispatcher"
	lokidispatcher "github.com/minuk-dev/opentelemetry-querier/dispatcher/lokidispatcher"
	prometheusdispatcher "github.com/minuk-dev/opentelemetry-querier/dispatcher/prometheusdispatcher"
	"github.com/minuk-dev/opentelemetry-querier/processor"
	authratelimitprocessor "github.com/minuk-dev/opentelemetry-querier/processor/authratelimitprocessor"
	queryrewriteprocessor "github.com/minuk-dev/opentelemetry-querier/processor/queryrewriteprocessor"
	responsefilterprocessor "github.com/minuk-dev/opentelemetry-querier/processor/responsefilterprocessor"
	simpleauthzprocessor "github.com/minuk-dev/opentelemetry-querier/processor/simpleauthzprocessor"
	tenantprocessor "github.com/minuk-dev/opentelemetry-querier/processor/tenantprocessor"
	"github.com/minuk-dev/opentelemetry-querier/querier"
)

// components registers the factories selected in builder.yaml.
func components() (querier.Factories, error) {
	var factories querier.Factories
	var err error

	if factories.Acceptors, err = acceptor.MakeFactoryMap(
		otqpacceptor.NewFactory(),
		prometheusacceptor.NewFactory(),
		lokiacceptor.NewFactory(),
	); err != nil {
		return factories, err
	}

	if factories.Processors, err = processor.MakeFactoryMap(
		authratelimitprocessor.NewFactory(),
		tenantprocessor.NewFactory(),
		queryrewriteprocessor.NewFactory(),
		responsefilterprocessor.NewFactory(),
		simpleauthzprocessor.NewFactory(),
	); err != nil {
		return factories, err
	}

	if factories.Dispatchers, err = dispatcher.MakeFactoryMap(
		prometheusdispatcher.NewFactory(),
		lokidispatcher.NewFactory(),
	); err != nil {
		return factories, err
	}

	return factories, nil
}
