name: Sync labels

on:
  push:
    branches: [main]
    paths:
      - .github/labels.yml
      - .github/workflows/labels.yml
  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  labeler:
    name: sync repo labels
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: crazy-max/ghaction-github-labeler@v5
        with:
          yaml-file: .github/labels.yml
          # Do not delete labels that are not listed here.
          skip-delete: true
